server:
  port: 8822

web:
  upload-path: F:/exhibition/
spring:
  datasource:
    url: jdbc:mysql://10.10.10.107:3306/exhibition-test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: ipos
    password: hongjipos@2016
    driver-class-name: com.mysql.jdbc.Driver


  thymeleaf:
    cache: false
    mode: HTML
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

mybatis:
  type-aliases-package: com.honji.exhibition


mybatis-plus:
    # 支持统配符 * 或者 ; 分割
    typeEnumsPackage: com.honji.exhibition.enums
    configuration:
      default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler


mapper:
  mappers:
  - tk.mybatis.mapper.common.Mapper
  not-empty: true

wx:
  mp:
    appId: wx85026c3b4d60d28d
    secret: aa9d98fe21d17bf9246a4c4c5892c012
    token:
    aesKey:
logging:

  file: logs/exhibition.log
  level:
    com.honji.exhibition.mapper: debug
    root: INFO
