server:
  port: 8000
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB
    session:
      timeout: 1h

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/exhibition?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


  thymeleaf:
    cache: false
    mode: HTML

mybatis:
  type-aliases-package: com.honji.exhibition


mybatis-plus:
    # 支持统配符 * 或者 ; 分割
    typeEnumsPackage: com.honji.exhibition.enums
    configuration:
      default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler


mapper:
  mappers:
  - tk.mybatis.mapper.common.Mapper
  not-empty: true

wx:
  mp:
    appId: wx2403fce351d2e3d8
    secret: f2dca5ef6d95b67e917790952087141d
    token: wff896uy53fr54l12xd954fgkl2qsa56
    aesKey: TrggU0NiO105hc7bK7DGZVF7CACo5vyu4YPb6FCB0A9
logging:

  file: logs/exhibition.log
  level:
    com.honji.exhibition.mapper: debug
    root: INFO
